# Generated by Django 5.2.3 on 2025-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='$', max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, help_text='$', max_digits=10)),
                ('debt', models.DecimalField(decimal_places=2, default=0, help_text='$', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='$', max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
