# Generated by Django 5.2.3 on 2025-08-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='៛')),
                ('pending_amount', models.IntegerField(default=0, help_text='៛')),
                ('debt', models.IntegerField(default=0, help_text='៛')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(help_text='៛')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'លុយ',
                'verbose_name_plural': 'លុយ',
            },
        ),
    ]
