# Generated by Django 5.2.3 on 2025-08-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='money',
            options={'verbose_name_plural': 'Money'},
        ),
    ]
