# Generated by Django 5.2.3 on 2025-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.JSONField(editable=False)),
                ('expected_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('final_quantity', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
