# Generated by Django 5.2.3 on 2025-08-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'រូបមន្ត',
                'verbose_name_plural': 'រូបមន្ត',
            },
        ),
        migrations.CreateModel(
            name='FormulaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('final_quantity', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'ផលិតកម្ម',
                'verbose_name_plural': 'ផលិតកម្ម',
            },
        ),
    ]
