# Generated by Django 5.2.3 on 2025-08-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='manufacturinglog',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.formula'),
        ),
    ]
