# Generated by Django 5.2.3 on 2025-08-13 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('process', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
        migrations.AddField(
            model_name='formulaitem',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='process.formula'),
        ),
        migrations.AddField(
            model_name='formulaitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.material'),
        ),
        migrations.AddField(
            model_name='manufacturinglog',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.formula'),
        ),
        migrations.AlterUniqueTogether(
            name='formula',
            unique_together={('product', 'expected_quantity')},
        ),
    ]
