# Generated by Django 5.2.3 on 2025-08-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturinglog',
            name='created_by',
        ),
    ]
