# Generated by Django 5.2.3 on 2025-08-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_remove_manufacturinglog_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturinglog',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
