# Generated by Django 5.2.3 on 2025-08-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_manufacturinglog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturinglog',
            name='material',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='manufacturinglog',
            name='product',
            field=models.JSONField(editable=False),
        ),
    ]
