# Generated by Django 5.2.3 on 2025-08-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(help_text='ថែម, ដាក់ - ពីមុខដើម្បីថយ')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'ថែមថយស្តុកគ្រឿង',
                'verbose_name_plural': 'ថែមថយស្តុកគ្រឿង',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('price', models.IntegerField(help_text='riel')),
                ('unit', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('pending_stock', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'ស្តុកគ្រឿង',
                'verbose_name_plural': 'ស្តុកគ្រឿង',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, editable=False, null=True)),
                ('done', models.BooleanField(default=False)),
                ('done_on', models.DateField(blank=True, editable=False, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('total_price', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'បុងទិញចូល',
                'verbose_name_plural': 'បុងទិញចូល',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'អ្នកផ្គត់ផ្គង់',
                'verbose_name_plural': 'អ្នកផ្គត់ផ្គង់',
            },
        ),
    ]
