# Generated by Django 5.2.3 on 2025-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='quantity',
            field=models.IntegerField(help_text='ថែម, ដើម្បីដកដាក់សញ្ញាដកពីមុខ'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
