# Generated by Django 5.2.3 on 2025-08-09 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_purchase_comment_purchase_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='final_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='បើមិនដាក់ វានឹងគណនាឲ្យ', max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='pending_stock',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='content',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='fulfilled_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
