# Generated by Django 5.2.3 on 2025-08-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(help_text='ថែម, ដាក់ - ពីមុខដើម្បីថយ')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'ថែមថយផលិតផល',
                'verbose_name_plural': 'ថែមថយផលិតផល',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=255, null=True, blank=True)),
                ('location', models.CharField(max_length=255, null=True, blank=True)),
            ],
            options={
                'verbose_name': 'អតិថិជន',
                'verbose_name_plural': 'អតិថិជន',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, editable=False, null=True)),
                ('done', models.BooleanField(default=False)),
                ('done_on', models.DateField(blank=True, editable=False, null=True)),
                ('content', models.JSONField(editable=False)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'បុងលក់ចេញ',
                'verbose_name_plural': 'បុងលក់ចេញ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('price', models.IntegerField(help_text='៛')),
                ('unit', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('pending_stock', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'ស្តុកផលិតផល',
                'verbose_name_plural': 'ស្តុកផលិតផល',
            },
        ),
    ]
