# Generated by Django 5.2.3 on 2025-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(help_text='ដកចេញ')),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactured_on', models.DateField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('paid_on', models.DateField(blank=True, editable=False, null=True)),
                ('fulfilled', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('fulfilled_on', models.DateField(blank=True, editable=False, null=True)),
                ('content', models.JSONField(editable=False)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='បើមិនដាក់ វានឹងគណនាឲ្យ', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='$', max_digits=10)),
                ('unit', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0, editable=False)),
                ('pending_stock', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
