# Generated by Django 5.2.3 on 2025-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='manufactured_on',
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='quantity',
            field=models.IntegerField(help_text='ថែម, ដើម្បីដកដាក់សញ្ញាដកពីមុខ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
