# Generated by Django 5.2.3 on 2025-08-08 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order_buyer_order_comment_order_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='$', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilled_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
